export const artistOptions = [
  { value: '1', ArtistId: '1', Name: 'The beatls' },
  { value: '2', ArtistId: '2', Name: 'SuperBeaver' },
  { value: '3', ArtistId: '3', Name: 'ive' },
  { value: '4', ArtistId: '4', Name: 'BTS' },
  { value: '5', ArtistId: '5', Name: '嵐' },
  { value: '6', ArtistId: '6', Name: '伊藤史人' },
  { value: '7', ArtistId: '7', Name: 'かなぶん' },
  { value: '8', ArtistId: '8', Name: 'あいこ' },
  { value: '9', ArtistId: '9', Name: 'queen' },
  { value: '10', ArtistId: '10', Name: 'radwimps' },
  { value: '11', ArtistId: '11', Name: 'The Fuhii' },
  { value: '12', ArtistId: '12', Name: 'いとう' },
  { value: '13', ArtistId: '13', Name: 'ふひいいい' },
  { value: '14', ArtistId: '14', Name: 'バレーボール' },
  { value: '15', ArtistId: '15', Name: 'プリン' },
]
